// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package db

import (
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializeDatabase() *gorm.DB {
	gormDB := newDatabase()
	return gormDB
}
