// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package auth

import (
	"github.com/nhatminhk63j/uetvoting/pkg/auth"
)

// Injectors from wire.go:

func InitializeHandler() *ServiceServer {
	service := auth.InitializeService()
	serviceServer := NewServiceServer(service)
	return serviceServer
}
