// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package event

import (
	"github.com/nhatminhk63j/uetvoting/pkg/db"
)

// Injectors from wire.go:

func InitializeRepo() Repository {
	gormDB := db.InitializeDatabase()
	repository := NewRepository(gormDB)
	return repository
}

func InitializeService() Service {
	repository := InitializeRepo()
	eventService := NewService(repository)
	return eventService
}
