// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package event

import (
	"github.com/nhatminhk63j/uetvoting/pkg/event"
)

// Injectors from wire.go:

func InitializeHandler() *ServiceServer {
	service := event.InitializeService()
	serviceServer := NewServiceServer(service)
	return serviceServer
}
