// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package auth

import (
	"github.com/nhatminhk63j/uetvoting/pkg/jwt"
	"github.com/nhatminhk63j/uetvoting/pkg/user"
)

// Injectors from wire.go:

func InitializeService() Service {
	resolver := jwt.NewJWTResolver()
	userService := user.InitializeService()
	authService := NewService(resolver, userService)
	return authService
}
