// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package user

import (
	"github.com/nhatminhk63j/uetvoting/pkg/db"
)

// Injectors from wire.go:

func InitializeRepository() Repository {
	gormDB := db.InitializeDatabase()
	repository := NewRepository(gormDB)
	return repository
}

func InitializeService() Service {
	repository := InitializeRepository()
	userService := NewService(repository)
	return userService
}
